# Generated by Django 3.2.2 on 2021-06-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lat',
            field=models.FloatField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='lng',
            field=models.FloatField(default='0', max_length=50),
        ),
    ]
